export default {
  login: 'christi023',
  id: 48160897,
  node_id: 'MDQ6VXNlcjQ4MTYwODk3',
  avatar_url: 'https://avatars1.githubusercontent.com/u/48160897?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/christi023',
  html_url: 'https://github.com/christi023',
  followers_url: 'https://api.github.com/users/christi023/followers',
  following_url: 'https://api.github.com/users/christi023/following{/other_user}',
  gists_url: 'https://api.github.com/users/christi023/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/christi023/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/christi023/subscriptions',
  organizations_url: 'https://api.github.com/users/christi023/orgs',
  repos_url: 'https://api.github.com/users/christi023/repos',
  events_url: 'https://api.github.com/users/christi023/events{/privacy}',
  received_events_url: 'https://api.github.com/users/christi023/received_events',
  type: 'User',
  site_admin: false,
  name: 'Sheliann Olsson',
  company: null,
  blog: 'https://sheliann-olsson-portfolio.netlify.com/',
  location: 'Malmö, Sweden',
  email: null,
  hireable: null,
  bio:
    ' I love using my creativities\r\nand skills to design websites, apps and more. I also love the mental challenge that programming\r\npresents.',
  twitter_username: null,
  public_repos: 119,
  public_gists: 3,
  followers: 11,
  following: 24,
  created_at: '2019-03-02T17:46:50Z',
  updated_at: '2020-10-16T16:42:41Z',
};
